
version: 2.1
jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            wget https://github.com/cli/cli/releases/download/v2.40.1/gh_2.40.1_linux_amd64.deb -O gh.deb
            sudo dpkg -i gh.deb
            echo "$(echo ${GITHUB_TOKEN} | gh auth login --with-token)"
            sudo apt update && sudo apt install -y bc bison build-essential ccache git-lfs curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3
      - run:
          name: Set up Repo And Sync PitchBlack Recovery Source
          command: |
            mkdir -p ~/android/pbrp
            cd ~/android/pbrp
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH=$PATH:~/bin/
            git config --global user.name "kelexine"
            git config --global user.email "frankiekelechi@gmail.com"
            repo init --depth=1 -u https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-11.0
            repo sync  --force-sync --current-branch --no-tags --no-clone-bundle --optimized-fetch --prune -j20
      - run:
          name: Clone Device Tree
          command: |
            cd ~/android/pbrp
            git clone https://github.com/kelexine/pbrp_device_tecno_kelly -b android-11 device/tecno/kelly
      - run:
          name: Start pbrp Build
          command: |
            cd ~/android/pbrp
            source build/envsetup.sh
            lunch omni_kelly-eng
            croot
            mka bootimage -j$(nproc --all)
            mka pbrp
            echo $CIRCLE_BUILD_NUM
      - run:
          name: Upload To GitHub
          command: |
            cd ~/android/pbrp
            cd device/tecno/kelly
            gh release create $CIRCLE_BUILD_NUM --latest --notes "This build is still in testing phase, so flash at your own risk" --title "pbrp recovery Build for Tecno Spark 8C (kelly)"  ~/android/pbrp/out/target/product/kelly/*.img
            gh release upload $CIRCLE_BUILD_NUM ~/android/pbrp/out/target/product/kelly/*.zip
      - store_artifacts:
            path: |
               ~/android/pbrp/out/target/product/kelly/*.zip
               ~/android/pbrp/out/target/product/kelly/*.img
workflows:
  main:
    jobs:
      - build
